return {
    ["SelectLanguage"] = "Select Language",
    ["LoadingAsset"] = "Loading Asset",
    ["LoadingData"] = "Loading Data",
    ["LoadingComplete"] = "Loading Complete",
    ["Loading"] = "Loading",

    ["Weapon"] = "Weapon",
    ["Boombox"] = "Boombox",
    ["Pet"] = "Pet",
    ["Inventory"] = "Inventory",
    ["Shop"] = "Shop",
    ["Game"] = "Game",
    ["Achievements"] = "Achievements",
    ["Setting"] = "Setting",
    ["Credits"] = "Credits",
    ["GhostBook"] = "Ghost Book",
    ["Hat"] = "Hat",

    ["Damage"] = "Damage",
    ["Rarity"] = "Rarity",

    ["Equip"] = "Equip",
    ["Equipped"] = "Equipped",

    ["Kill"] = "Kill",
    ["Headshot"] = "Headshot",
    ["Assist"] = "Assist",
    ["Leaderboard"] = "Leaderboard",
    ["Name"] = "Name",
    ["HighestWave"] = "Highest Wave",

    ["RevivePossessed"] = "PRESS <b>[ F ]</b> TO REVIVE",
    ["PlayerPossessed"] = "%s Has Been Possessed",

    ["KillEnemy"] = "[R +%s] [XP +%s] Kill %s",
    ["AssistEnemy"] = "[R +%s] [XP +%s] [Assist] Kill %s",
    ["HeadshotEnemy"] = "[R +%s] [XP +%s] <font color='rgb(255,0,0)'>[Headshot]</font> Kill %s",
    ["SurviveRound"] = "[R +%s] [XP +%s] Survive Round",
    ["SurviveRoundBoss"] = "[R +%s] [XP +%s] You Guys Success Kill The Boss!",

    ["NoPlayerIntermission"] = "There is no player in this server, do intermission again...",
    ["LoadingMap"] = "Loading map",
    ["Gameover"] = "Game over",
    ["EndWave"] = "Wave %s over",
    ["StartWave"] = "Starting Wave %s",
    ["TeleportingPlayer"] = "Teleporting player",
    ["Intermission"] = "Intermission %s",
    ["Gameplay"] = "Wave %s | %s Ghost(s) Left | Time Left %s",
    ["GameplayBoss"] = "Wave Boss | Kill The Boss | Time Left %s",

    ["Attack"] = "Attack",
    ["Shot"] = "Shot",
    ["Menu"] = "Menu",
    ["Dash"] = "Dash",
    ["Revive"] = "Revive",

    ["NoPlayerSpectate"] = "There is no player you can spectate",
    ["SpectateNote"] = "You are spectating right now. To quit, press [ T ]",
    ["Spectate"] = "Spectate",

    ["GameTutorial"] = "Game Tutorial",
    ["GameTutorialNote"] = "How to play? Kill the ghost with weapon, press [ 1 ] [ 2 ] to equip weapon. If you're on mobile, click box button in the middle bottom. This game is basically like another zombie wave game in roblox",
    ["Control"] = "Controls",
    ["ControlNote"] = "Inventory - [ I ]<br />Spectate - [ T ]<br />Leaderboard - [ Tab ]<br />Dash - [ Space ]<br />Change Weapon - [ 1 ] [ 2 ]",
    ["Close"] = "Close",
    ["GameTutorialClose"] = "Press [ Space ] or Click This to Close",

    ["FeedbackInteract"] = "PRESS <b>[ F ]</b> TO OPEN FEEDBACK CENTER",
    ["FeedbackTitle"] = "Feedback Center",
    ["FeedbackSend"] = "Send To Developer",
    ["FeedbackSendLater"] = "Send feedback later",
    ["FeedbackCooldown"] = "Cooldown (%s)",
    ["FeedbackNotValid"] = "Feedback must be more than 5 character",
    ["FeedbackSended"] = "Feedback sent to Developer",
    ["FeedbackMessage"] = "Write your feedback here",
    ["Open"] = "Open",

    ["YouDied"] = "You Died",
    ["JoinGame"] = "Join Game",
    ["JoinGameInteract"] = "PRESS <b>[ G ]</b> TO JOIN GAME",
    ["BossMode"] = "Boss Mode!",
    ["AngryMode"] = "Angry Mode",
    ["Possessed"] = "Possessed",

    ["Aim"] = "Aim",
    ["Language"] = "Language",
    ["Shadow"] = "Shadow",
    ["KillEffect"] = "Kill Effect",
    ["OrbEffect"] = "Orb Effect",
    ["DashEffect"] = "DashEffect",
    ["Blood"] = "Blood",
    ["LobbyMusic"] = "Lobby Music",
    ["CameraMode"] = "Camera Mode",
    ["Off"] = "Off",
    ["On"] = "On",
    ["Yes"] = "Yes",
    ["No"] = "No",
    ["EquipNow"] = "Equip now?",
    ["Buy"] = "Buy",
    ["Cancel"] = "Cancel",
    ["BuyWhat"] = "Do you want to buy [%s]?",
    ["Price"] = "Price",
    ["FailedBuy"] = "Failed to buy",
    ["SuccessBuy"] = "Success to buy",
    ["AlreadyBuy"] = "You already buy the item",
    ["Money"] = "Money",
    ["MoneyNotEnough"] = "Your money not enough",
    ["MapCinematic"] = "%s Created by %s",
    ["BoughtAllStuff"] = "You Already Bought all stuff!"
}
