return {
    ["SelectLanguage"] = "Pilih Bahasa",
    ["LoadingAsset"] = "Sedang Memuat Asset",
    ["LoadingData"] = "Sedang Memuat Data",
    ["LoadingComplete"] = "Telah Selesai Memuat",
    ["Loading"] = "Sedang Memuat",

    ["Weapon"] = "Senjata",
    ["Boombox"] = "Boombox",
    ["Pet"] = "Pet",
    ["Inventory"] = "Inventory",
    ["Shop"] = "Toko",
    ["Game"] = "Game",
    ["Achievements"] = "Prestasi",
    ["Setting"] = "Pengaturan",
    ["Credits"] = "Credits",
    ["GhostBook"] = "Buku Hantu",
    ["Hat"] = "Topi",

    ["Damage"] = "Kekuatan",
    ["Rarity"] = "Kelangkaan",

    ["Equip"] = "Pasang",
    ["Equipped"] = "Terpasang",

    ["Kill"] = "Membunuh",
    ["Headshot"] = "Headshot",
    ["Assist"] = "Membantu",
    ["Leaderboard"] = "Papan Pemimpin",
    ["Name"] = "Nama",
    ["HighestWave"] = "Gelombang Tertinggi",

    ["RevivePossessed"] = "TEKAN <b>[ F ]</b> UNTUK MENYELAMATKAN",
    ["PlayerPossessed"] = "%s Telah Kesurupan",

    ["KillEnemy"] = "[R +%s] [XP +%s] Membunuh %s",
    ["AssistEnemy"] = "[R +%s] [XP +%s] [Bantu] Membunuh %s",
    ["HeadshotEnemy"] = "[R +%s] [XP +%s] <font color='rgb(255,0,0)'>[Headshot]</font> Membunuh %s",
    ["SurviveRound"] = "[R +%s] [XP +%s] Berhasil Bertahan Hidup",
    ["SurviveRoundBoss"] = "[R +%s] [XP +%s] Kalian Sukses Membunuh Bos!",

    ["NoPlayerIntermission"] = "Tidak ada pemain, Melakukan istirahat lagi .. ",
    ["LoadingMap"] = "Memuat peta",
    ["Gameover"] = "Permainan berakhir",
    ["EndWave"] = "Gelombang %s berakhir",
    ["StartWave"] = "Memulai gelombang %s",
    ["TeleportingPlayer"] = "Pemain diteleportasi",
    ["Intermission"] = "Istirahat  %s",
    ["Gameplay"] = "Gelombang %s | %s Hantu Tersisa | Waktu Tersisa %s",
    ["GameplayBoss"] = "Gelombang Bos | Bunuh Bos | Waktu Tersisa %s",

    ["Attack"] = "Serang",
    ["Shot"] = "Tembak",
    ["Menu"] = "Menu",
    ["Dash"] = "Dash",
    ["Revive"] = "Revive",

    ["NoPlayerSpectate"] = "Tidak ada pemain yang bisa Anda tonton",
    ["SpectateNote"] = "Anda sedang menononton sekarang, untuk keluar tekan [ T ]",
    ["Spectate"] = "Nonton",

    ["GameTutorial"] = "Tutorial Permainan",
    ["GameTutorialNote"] = "Bagaimana cara bermain? ya bunuh hantunya pake senjata, tekan [ 1 ] [ 2 ] untuk pake senjata atau jika di HP/Tablet klik tombol kotak di tenggah bawah, game ini pada dasarnya kek game zombie di roblox",
    ["Control"] = "Controls",
    ["ControlNote"] = "Menu - [ M ]<br />Nonton - [ T ]<br />Papan Pemimpin - [ Tab ]<br />Dash - [ Q ]<br />Lompat - [ Space ]<br />Ganti Senjata - [ 1 ] [ 2 ]",
    ["Close"] = "Tutup",
    ["GameTutorialClose"] = "Tekan [ Space ] atau Klik Ini untuk Menutup",

    ["FeedbackInteract"] = "TEKAN <b>[ F ]</b> UNTUK MEMBERIKAN MASUKAN",
    ["FeedbackTitle"] = "Pusat Masukan",
    ["FeedbackSend"] = "Kirim Ke Developer",
    ["FeedbackSendLater"] = "Kirim masukan nanti",
    ["FeedbackCooldown"] = "Cooldown (%s)",
    ["FeedbackNotValid"] = "Masukan harus lebih dari 5 kata",
    ["FeedbackSended"] = "Masukan terkirim ke Developer",
    ["FeedbackMessage"] = "Tulis masukanmu disini",
    ["Open"] = "Buka",

    ["YouDied"] = "Kamu Mati",
    ["JoinGame"] = "Join Game",
    ["JoinGameInteract"] = "TEKAN <b>[ G ]</b> UNTUK JOIN GAME",
    ["BossMode"] = "Mode Bos!",
    ["AngryMode"] = "Mode Marah",
    ["Possessed"] = "Kesurupan",

    ["Aim"] = "Aim",
    ["Language"] = "Bahasa",
    ["Shadow"] = "Shadow",
    ["KillEffect"] = "Efek Mati",
    ["OrbEffect"] = "Efek Orb",
    ["DashEffect"] = "Efek Dash",
    ["Blood"] = "Darah",
    ["LobbyMusic"] = "Musik Lobi",
    ["CameraMode"] = "Mode Kamera",
    ["Off"] = "Mati",
    ["On"] = "Nyala",
    ["Yes"] = "Ya",
    ["No"] = "Tidak",
    ["EquipNow"] = "Pasang sekarang?",
    ["Buy"] = "Beli",
    ["Cancel"] = "Batal",
    ["BuyWhat"] = "Apakah kamu ingin membeli [%s]?",
    ["Price"] = "Harga",
    ["FailedBuy"] = "Gagal membeli",
    ["SuccessBuy"] = "Berhasil membeli",
    ["AlreadyBuy"] = "Kamu sudah membeli item ini",
    ["Money"] = "Uang",
    ["MoneyNotEnough"] = "Uang kamu tidak cukup",
    ["MapCinematic"] = "%s Dibuat oleh %s",
    ["BoughtAllStuff"] = "Anda Sudah Membeli semua barang!",

    ["CodeError"] = "Kode salah atau sudah kedaluwarsa",
    ["CodeSuccess"] = "Kode berhasil dipakai, Kamu mendapatkan %s",
    ["CodeInput"] = "Masukan kodemu disini",
    ["CodeTitle"] = "Promo Kode",
    ["CodeNote"] = "Kamu bisa mendapatkan kode dari Server Komunitas/Forum atau Group Shout di bakahu group",

    ["Play"] = "Mulai",
    ["EmoteNote"] = "tekan 1 - 4 atau klik kotak untuk memainkan emote"
}
